### ISSUE TITLE
Local installation via go get

### ISSUE THREAD

**Issue by rubisco57** [lsvx/drae#4]
Hi squat, 
I am  interested in your API project.
Since I am new to the Go programming language, I would really appreciate, if you considered elaborating the local install section a little more. The `go get` command failed as there were 

> no Go files in /home/lea/go/src/github.com/squat/drae

I installed the most recent Go version 1.9.
Thanks in advance for your advice.

**Comment by squat** [comment]
@rubisco57 sorry I didn't see this issue earlier. This was indeed a documentation problem that surfaced when I restructured the project. Please try again now with the updated documentation, namely:
```
go get -u github.com/squat/drae/cmd/drae
```
Please re-open the issue if you continue to experience this issue.
