### ISSUE TITLE
failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by foolishwang** [lsvx/drae#5]
time="2019-02-09T06:39:33Z" level=error msg="failed to define word: failed to make request to rae: Get https://dle.rae.es/srv/search?w=gato: x509: failed to load system roots and no roots provided"

**Comment by squat** [comment]
Hi, this error is saying that the binary cannot find the root CA certificates that should be installed on every system. How are you running drae? Are you running the binary directly on you machine, the squat/drae container, or some other way? Also, what is your environment/os?

**Comment by squat** [comment]
Closing due to no response. Please reopen if it's still and issue :)
